# Change these first
owner: opogo # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Opogo Site
    url: https://www.opogo.com/
  - name: API
    url: https://api.opogo.com
  - name: CMS
    url: https://cms.opogo.com
  - name: App
    url: https://app.opogo.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://uploads-ssl.webflow.com/5efc914efa5a4981b1c507f9/5efc95c7d218909fe996b5b4_OPOGO_LOGO.png
  name: Opogo Uptime
  introTitle: "**Opogo** A Social Enterprise."
  introMessage: Status page for Opogo systems
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
